### ISSUE TITLE
Any examples on how to use this ?

### ISSUE THREAD

**Issue by wzymaster** [quixey/python-aliyun#20]
I am looking for some examples on how to use this lib so that I can easily use it in my python app, like : 

1) create  instance
2) create disk 
3) attach disk
4) start instance
5) delete instance

Your help is highly appreciated !

**Comment by wzymaster** [comment]
I figure it out by walking through unit test codes. thanks.

**Comment by addumb** [comment]
Could you update here with what you put together? It might be nice to add an examples/ directory or something like that for common recipes.
